const columnsClientsConfig = [
  {
    id: "dataUtworzenia",
    label: "Data Utworzenia",
    shortLabel: "Utworz.",
    type: "datetime",
    sortable: true,
    view: "basic",
  },
  {
    id: "dataZapytania",
    label: "Data zapytania",
    shortLabel: "Zapyt.",
    type: "datetime",
    sortable: true,
    view: "basic",
  },
  {
    id: "dataNastepnegoKontaktu",
    label: "Data następnego kontaktu",
    shortLabel: "Nast. Kontakt",
    type: "datetime",
    sortable: true,
    view: "basic",
  },
  {
    id: "ostatniKontakt",
    label: "Ostatni kontakt",
    shortLabel: "Ost. Kontakt",
    type: "datetime",
    sortable: true,
    view: "basic",
  },
  {
    id: "daneKlienta",
    label: "Dane klienta",
    shortLabel: "Klient",
    type: "string",
    sortable: true,
    view: "basic",
  },
  {
    id: "numerTelefonu",
    label: "Numer telefonu",
    shortLabel: "Tel.",
    type: "number",
    sortable: false,
    view: "basic",
  },
  {
    id: "adresEmail",
    label: "Adres e-mail",
    shortLabel: "Email",
    type: "string",
    sortable: false,
    view: "basic",
  },
  {
    id: "komentarzData",
    label: "Komentarz dot. następnego kontaktu",
    shortLabel: "Koment. nast. k.",
    sortable: false,
    view: "basic",
  },
  {
    id: "numerGalactica",
    label: "Numer oferty w Galactice",
    shortLabel: "Galact.",
    type: "string",
    sortable: false,
    view: "basic",
  },
  {
    id: "status",
    label: "Status",
    shortLabel: "Status",
    type: "dictionary",
    sortable: false,
    view: "basic",
  },
  {
    id: "agent",
    label: "Agent",
    shortLabel: "Agent",
    type: "dictionary",
    sortable: true,
    view: "basic",
  },
  {
    id: "komentarz",
    label: "Opis klienta",
    shortLabel: "Opis",
    sortable: false,
    view: "basic",
  },
  {
    id: "portal",
    label: "Portal",
    shortLabel: "Portal",
    view: "basic",
  },
  {
    id: "lokalizacja",
    label: "Lokalizacja",
    shortLabel: "Lok.",
    type: "dictionary",
    sortable: false,
    view: "basic",
  },
  {
    id: "rodzajNieruchomosci",
    label: "Rodzaj nieruchomości",
    shortLabel: "Typ",
    type: "dictionary",
    sortable: false,
    view: "basic",
  },
  {
    id: "iloscPokoiOd",
    label: "Ilość pokoi od",
    shortLabel: "Pokoje Od",
    type: "number",
    sortable: true,
    view: "basic",
  },
  {
    id: "iloscPokoiDo",
    label: "Ilość pokoi do",
    shortLabel: "Pokoje Do",
    type: "number",
    sortable: true,
    view: "basic",
  },
  {
    id: "metrazOd",
    label: "Metraż od",
    shortLabel: "Metraż Od",
    type: "number",
    sortable: true,
    view: "basic",
  },
  {
    id: "metrazDo",
    label: "Metraż do",
    shortLabel: "Metraż Do",
    type: "number",
    sortable: true,
    view: "basic",
  },
  {
    id: "standard",
    label: "Standard",
    shortLabel: "Stand.",
    type: "dictionary", // Słownik: Do wejścia, Do remontu, Deweloperski, Do odświeżenia
    sortable: false,
    view: "basic",
  },
  {
    id: "budzetOd",
    label: "Budżet od",
    shortLabel: "Budżet Od",
    type: "number",
    sortable: true,
    view: "basic",
  },
  {
    id: "budzetDo",
    label: "Budżet do",
    shortLabel: "Budżet Do",
    type: "number",
    sortable: true,
    view: "basic",
  },
];

export default columnsClientsConfig;
