const columnsOffersConfig = [
  {
    id: "linkOferta",
    label: "Link",
    shortLabel: "Link",
    sortable: false,
    view: "extended",
  },
  {
    id: "dataNastepnegoKontaktu",
    label: "Data następnego kontaktu",
    shortLabel: "Następny",
    sortable: true,
    view: "extended",
  },
  {
    id: "dataKontaktu",
    label: "Data kontaktu",
    shortLabel: "Kont.",
    sortable: true,
    view: "extended",
  },
  {
    id: "status",
    label: "Status",
    shortLabel: "Status",
    sortable: false,
    view: "basic",
  },
  {
    id: "agent",
    label: "Agent",
    shortLabel: "Agent",
    sortable: true,
    view: "basic",
  },
  {
    id: "komentarz",
    label: "Komentarz",
    shortLabel: "Koment.",
    sortable: false,
    view: "extended",
  },
  {
    id: "daneWlasciciela",
    label: "Dane właściciela",
    shortLabel: "Właściciel",
    sortable: true,
    view: "extended",
  },
  {
    id: "telefonDoWlasciciela",
    label: "Telefon",
    shortLabel: "Tel.",
    sortable: false,
    view: "basic",
  },
  {
    id: "zlM2",
    label: "Zł/M2",
    shortLabel: "Zł/M2",
    sortable: true,
    view: "extended",
  },
  {
    id: "cena",
    label: "Cena",
    shortLabel: "Cena",
    sortable: true,
    view: "basic",
  },
  {
    id: "powDzialki",
    label: "Powierzchnia działki",
    shortLabel: "Działka",
    sortable: true,
    view: "extended",
  },
  {
    id: "metraz",
    label: "Metraż",
    shortLabel: "M2",
    sortable: true,
    view: "basic",
  },
  {
    id: "iloscPokoi",
    label: "Ilość pokoi",
    shortLabel: "Pok.",
    sortable: true,
    view: "basic",
  },
  {
    id: "typInwestycji",
    label: "Typ inwestycji",
    shortLabel: "Typ",
    sortable: false,
    view: "basic",
  },
  {
    id: "rynek",
    label: "Rynek",
    shortLabel: "Rynek",
    sortable: false,
    view: "extended",
  },
  {
    id: "miasto",
    label: "Miasto/Wieś",
    shortLabel: "Miasto",
    sortable: true,
    view: "extended",
  },

  {
    id: "dzielnica",
    label: "Dzielnica/Gmina",
    shortLabel: "Dziel.",
    sortable: true,
    view: "basic",
  },
  {
    id: "poddzielnica",
    label: "Poddzielnica",
    shortLabel: "Poddz.",
    sortable: true,
    view: "extended",
  },
  {
    id: "ulica",
    label: "Ulica",
    shortLabel: "Ul.",
    sortable: true,
    view: "basic",
  },
];

export default columnsOffersConfig;
