/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-north-1",
  aws_cognito_identity_pool_id:
    "eu-north-1:38049532-d688-4ce9-91f0-feb7e2d98542",
  aws_cognito_region: "eu-north-1",
  aws_user_pools_id: "eu-north-1_l1oYUM0xf",
  aws_user_pools_web_client_id: "3cver6p9h5ev10kbhe0n57is3r",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
